### ISSUE TITLE
No change in delay option in config.toml 

### ISSUE THREAD

**Issue by UmpquaRiver** [mrsobakin/lrc-dl#3]
I seem to be running into what I believe to be rate limiting errors when using the MusixMatch provider:

> [musixmatch] Fetching lyrics...
[musixmatch] Got exception while fetching lyrics! (KeyError: 'body')
[musixmatch] Traceback (most recent call last):
  File "/home/jayj/.local/lib/python3.12/site-packages/lrc_dl/__init__.py", line 46, in fetch_lyrics
    lyrics = provider.fetch_lyrics(song)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jayj/.local/lib/python3.12/site-packages/lrc_dl/providers/musixmatch.py", line 31, in fetch_lyrics
    response = response["message"]["body"]["macro_calls"]["track.subtitles.get"]["message"]["body"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'body'

I noticed that waiting 30-60 seconds between manual runs of the software usually fixes this error. I found during setup and in the README that the software already has an option in config.toml to change the delay. The default is `delay = 10` so I updated it to `delay = 40` but when I run it on a folder I still get the 10 second search delay.

> [lrc-dl] Sleeping for 10.00s...

I am using -c to specify the location of config.toml, and I believe lrc-dl _is_ using it because requests are going through to MusixMatch with the token specified therein.

I might suggest that the sleep time be increased by default if these are rate limiting related errors.

Installed via README instructions on Fedora Workstation 40

**Comment by mrsobakin** [comment]
I've uploaded a fix. Your suggestion from #4 is also now implemented.
